import { Suspense } from 'react'
import type { Metadata } from 'next'
import { createClient } from '@supabase/supabase-js'
import { notFound } from 'next/navigation'
import { LoyaltyHub } from './loyalty-hub'
import { loadMemberPage } from '@/lib/services/member-page-service'

type Props = {
  params: Promise<{ memberId: string }>
  searchParams: Promise<{ token?: string | string[] }>
}

// Rich link preview (studio name + branded image) so the onboarding link
// unfurls with the studio's identity when shared in iMessage / WhatsApp / etc.
// The branded image itself is generated by opengraph-image.tsx in this folder.
export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { memberId } = await params
  const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  )

  const select = 'studios:studio_id(name)'
  const { data: byMemberId } = await supabase.from('customers').select(select).eq('member_id', memberId).single()
  const customer = byMemberId ?? (await supabase.from('customers').select(select).eq('id', memberId).single()).data

  const studio = customer?.studios as unknown as { name: string } | null
  const studioName = studio?.name ?? 'Loyalink'

  const title = `${studioName} — Your loyalty card`
  const description = `Add your ${studioName} loyalty card to Apple or Google Wallet and start earning rewards.`

  return {
    title,
    description,
    openGraph: { title, description, type: 'website' },
    twitter: { card: 'summary_large_image', title, description },
  }
}

export default async function LoyaltyPage({ params, searchParams }: Props) {
  const { memberId } = await params
  const { token } = await searchParams
  // Personal data needs ?token= (see loadMemberPage). Without it the page is
  // the public card view: Add to Wallet and the studio's referral offer.
  const page = await loadMemberPage(memberId, typeof token === 'string' ? token : null)
  if (!page) notFound()

  return (
    <Suspense>
      <LoyaltyHub memberId={memberId} {...page} />
    </Suspense>
  )
}
